[[gawk]]
arch = "aarch64"
git-tree-sha1 = "54df850789d336a5ffb88744e1997f0284f67d60"
os = "macos"

    [[gawk.download]]
    sha256 = "0bc8b0e78e1b2630ee95803ee49d61da6e3a6e442f2029f595109fd54e0eb377"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.3.2+0/gawk.v5.3.2.aarch64-apple-darwin.tar.gz"
[[gawk]]
arch = "aarch64"
git-tree-sha1 = "56fafc0d6ad98c1b979c8f99b2ff0494f8127354"
libc = "glibc"
os = "linux"

    [[gawk.download]]
    sha256 = "f9406deece3105c4fb06a4cedb211be642b1a448166351b3c8204f9201b29cb1"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.3.2+0/gawk.v5.3.2.aarch64-linux-gnu.tar.gz"
[[gawk]]
arch = "aarch64"
git-tree-sha1 = "a5e79dd1fa318fc7701bde3a16426eac499e4086"
libc = "musl"
os = "linux"

    [[gawk.download]]
    sha256 = "6fb98920c5e793514fc1707ee78b52497197e7953ef5663477c132985d4ae0af"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.3.2+0/gawk.v5.3.2.aarch64-linux-musl.tar.gz"
[[gawk]]
arch = "aarch64"
git-tree-sha1 = "6089cfadef54a0d19f408c993fb7c5fed42d4625"
os = "freebsd"

    [[gawk.download]]
    sha256 = "dbf02736b7bc9828d5c69a8b6d1911f5cad1232f22fb57382020360e8f6f3472"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.3.2+0/gawk.v5.3.2.aarch64-unknown-freebsd.tar.gz"
[[gawk]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b0b7cbdfb6c89b7ce9cf943c7c316728f732a8a1"
libc = "glibc"
os = "linux"

    [[gawk.download]]
    sha256 = "7b22f8f899b2a1ce6aa4c75f4c886b6edf59e7ea319d61ace5fb99577989effc"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.3.2+0/gawk.v5.3.2.armv6l-linux-gnueabihf.tar.gz"
[[gawk]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c5d4831f2bf3b867039024e6001f3345027e38ec"
libc = "musl"
os = "linux"

    [[gawk.download]]
    sha256 = "eff4c23981fc7da5b7eaa4602e2243f272ead1cb4d1893d25306da4216d4210b"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.3.2+0/gawk.v5.3.2.armv6l-linux-musleabihf.tar.gz"
[[gawk]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0898ad62dde952edb9c0ddb5c40cd534e06c649d"
libc = "glibc"
os = "linux"

    [[gawk.download]]
    sha256 = "88bd6df9b4b98035134874063df0d54213a78f38eab300a5abaa0e3a85a96066"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.3.2+0/gawk.v5.3.2.armv7l-linux-gnueabihf.tar.gz"
[[gawk]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "afa0cfbe20c81b67a73a00bc52cee88cf3f5f2cd"
libc = "musl"
os = "linux"

    [[gawk.download]]
    sha256 = "2ea1a7e35da394065f907d155583171adb55496527c37dd7a85fda030f9e5911"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.3.2+0/gawk.v5.3.2.armv7l-linux-musleabihf.tar.gz"
[[gawk]]
arch = "i686"
git-tree-sha1 = "9e26ed3ce7f8df429977bd7eada1a685f2d6ebb7"
libc = "glibc"
os = "linux"

    [[gawk.download]]
    sha256 = "974c8c9a71ecd357a12bae66ce640d3b71d3c871122177f4cab4c12684486dd1"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.3.2+0/gawk.v5.3.2.i686-linux-gnu.tar.gz"
[[gawk]]
arch = "i686"
git-tree-sha1 = "0473f60f7d04d1df99412f273cf8f3b34a767e3a"
libc = "musl"
os = "linux"

    [[gawk.download]]
    sha256 = "7c5201d5c20c1d21ad3c368822efa648cb561076b04afe448cd6ec0989cd6aea"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.3.2+0/gawk.v5.3.2.i686-linux-musl.tar.gz"
[[gawk]]
arch = "powerpc64le"
git-tree-sha1 = "b96a2a2f30296d5f5c35dfdaf223e17fc73cd109"
libc = "glibc"
os = "linux"

    [[gawk.download]]
    sha256 = "077a412022ff8e421c1c5be1a5f3ce122009ca06a312dd47048a72719fa16fc8"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.3.2+0/gawk.v5.3.2.powerpc64le-linux-gnu.tar.gz"
[[gawk]]
arch = "riscv64"
git-tree-sha1 = "9538e0829ea3ff034da2fa5e4cb1d84ea174b956"
libc = "glibc"
os = "linux"

    [[gawk.download]]
    sha256 = "7ab5b1a48b1f36617710f6091a33043cafc09621b8030d0bc5d1fa840795dc31"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.3.2+0/gawk.v5.3.2.riscv64-linux-gnu.tar.gz"
[[gawk]]
arch = "x86_64"
git-tree-sha1 = "ac02f336ac6586428494d7bb8d4cd3cb2ca4dccb"
os = "macos"

    [[gawk.download]]
    sha256 = "cb506547366d06245457eb7f3c604b7ea515c4f672ce935484ab5d15421940b4"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.3.2+0/gawk.v5.3.2.x86_64-apple-darwin.tar.gz"
[[gawk]]
arch = "x86_64"
git-tree-sha1 = "ab10313c42366e83e6dabbd7de9facd5def2aa45"
libc = "glibc"
os = "linux"

    [[gawk.download]]
    sha256 = "ba0aab3fbe5a0cde1820ba75e989dcc3406d8c2b3e07ed15824ebafac5f730e8"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.3.2+0/gawk.v5.3.2.x86_64-linux-gnu.tar.gz"
[[gawk]]
arch = "x86_64"
git-tree-sha1 = "45870670e7962bfe9e297dea826ea2840dfad8cc"
libc = "musl"
os = "linux"

    [[gawk.download]]
    sha256 = "aa5d38470e3c147bb4fe6ba3bca62a5c29b9ba4debdb078c9e43a63d9e304d29"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.3.2+0/gawk.v5.3.2.x86_64-linux-musl.tar.gz"
[[gawk]]
arch = "x86_64"
git-tree-sha1 = "7bb54f0b64207f7f2169a69a0c88c3b61f0961ee"
os = "freebsd"

    [[gawk.download]]
    sha256 = "e7784396496dae2c286c82f6199dad527cf56282590936c54226b6f5ad9ecd6c"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.3.2+0/gawk.v5.3.2.x86_64-unknown-freebsd.tar.gz"
