[[gawk]]
arch = "aarch64"
git-tree-sha1 = "800d06edbdf8995a116fcef54e036084ebeb5752"
os = "macos"

    [[gawk.download]]
    sha256 = "adf18fcada7e5cda7d582337c90a0b88f4508175a5ce95ba233012ae485ee539"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.3.1+0/gawk.v5.3.1.aarch64-apple-darwin.tar.gz"
[[gawk]]
arch = "aarch64"
git-tree-sha1 = "5f62c2e55dba5a5bab1b4e0afce3a847e2ce763b"
libc = "glibc"
os = "linux"

    [[gawk.download]]
    sha256 = "424fa2b3b3c1a2bded11df5cfa5a68be30f7412ae84d6ec9d076e8b9b6b8b64a"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.3.1+0/gawk.v5.3.1.aarch64-linux-gnu.tar.gz"
[[gawk]]
arch = "aarch64"
git-tree-sha1 = "7fc09c49e4e1d9d725a8490f96cb38bb87a01440"
libc = "musl"
os = "linux"

    [[gawk.download]]
    sha256 = "b155b90bdf55f4ae54a58472dabbe5fb520a0f2c5280b38d5accb2aad0e6bc6d"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.3.1+0/gawk.v5.3.1.aarch64-linux-musl.tar.gz"
[[gawk]]
arch = "aarch64"
git-tree-sha1 = "c3a362a536a770a8df23b44d2052762909631aed"
os = "freebsd"

    [[gawk.download]]
    sha256 = "f88a9bb4daa1cc2b8a66c392333b8500823a170864fdbf2d5accc1fce3892bbc"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.3.1+0/gawk.v5.3.1.aarch64-unknown-freebsd.tar.gz"
[[gawk]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e424983a632834459ed6e9145f3de8aad8a1480b"
libc = "glibc"
os = "linux"

    [[gawk.download]]
    sha256 = "cd0e760c47b40eab8c4fa5fc027a54a032c451602d7dce250fd2d9fa098f470b"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.3.1+0/gawk.v5.3.1.armv6l-linux-gnueabihf.tar.gz"
[[gawk]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "919f6eddd0c6ac0635cdcc2e908279c99fd0a0ee"
libc = "musl"
os = "linux"

    [[gawk.download]]
    sha256 = "da08d9257197559ed19116d3327e1a7cd4ddc0a35a55e4b9993578edc3bc8d77"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.3.1+0/gawk.v5.3.1.armv6l-linux-musleabihf.tar.gz"
[[gawk]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6cc8ca022c1a594645039a02da14c94b12534a51"
libc = "glibc"
os = "linux"

    [[gawk.download]]
    sha256 = "65f872532577178c1977719dceda91698167c027a0dc1c840eab5ca04848c285"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.3.1+0/gawk.v5.3.1.armv7l-linux-gnueabihf.tar.gz"
[[gawk]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ff5d6e3030060d08273db87b70c20a6157568413"
libc = "musl"
os = "linux"

    [[gawk.download]]
    sha256 = "73852c56044bb4303de4dde0cfd350be0c34ce47845fa9371fdb6dc1f1dcb919"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.3.1+0/gawk.v5.3.1.armv7l-linux-musleabihf.tar.gz"
[[gawk]]
arch = "i686"
git-tree-sha1 = "f99af4886cf3b720530993ebc26799f2e58a15b9"
libc = "glibc"
os = "linux"

    [[gawk.download]]
    sha256 = "c6f8c08e49c71132e4dc9da95bdc25096886491ded8bfaa92a5b0e1bea277b79"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.3.1+0/gawk.v5.3.1.i686-linux-gnu.tar.gz"
[[gawk]]
arch = "i686"
git-tree-sha1 = "7e3b2ca9ccad7b20e60bc88a14f3a201955f93f3"
libc = "musl"
os = "linux"

    [[gawk.download]]
    sha256 = "d53a6bf5cef80ed012a69c3d408c919715497ce9a2f58a630803c22dc6f9682f"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.3.1+0/gawk.v5.3.1.i686-linux-musl.tar.gz"
[[gawk]]
arch = "powerpc64le"
git-tree-sha1 = "b5ca3b7891a99d13a4019a3e560a5f461ddffd6f"
libc = "glibc"
os = "linux"

    [[gawk.download]]
    sha256 = "bae5c137aa846871f73af25236777c12f584f2068ce9b939720fb04dbae290ec"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.3.1+0/gawk.v5.3.1.powerpc64le-linux-gnu.tar.gz"
[[gawk]]
arch = "x86_64"
git-tree-sha1 = "694e0a2585b4a399afe596245e09c0a5bcc94a4b"
os = "macos"

    [[gawk.download]]
    sha256 = "a6ce4e8cf2034439d1098ffe434f7bdeeeae119f3799190f201718dfbcacd2d6"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.3.1+0/gawk.v5.3.1.x86_64-apple-darwin.tar.gz"
[[gawk]]
arch = "x86_64"
git-tree-sha1 = "89e8680fdb13a56c35e2ac5197b08e764ca08fbc"
libc = "glibc"
os = "linux"

    [[gawk.download]]
    sha256 = "1d36c31d762c6d9d2b941a85897d0b959a220590c17ef93871650056ed28d441"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.3.1+0/gawk.v5.3.1.x86_64-linux-gnu.tar.gz"
[[gawk]]
arch = "x86_64"
git-tree-sha1 = "c440b97320d5e1f2e23a15256516147ee614d4ff"
libc = "musl"
os = "linux"

    [[gawk.download]]
    sha256 = "543131d918fc4ef92020fee0cc7538bcd4426e4fdfdb57a54b276fcfd8cd08b3"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.3.1+0/gawk.v5.3.1.x86_64-linux-musl.tar.gz"
[[gawk]]
arch = "x86_64"
git-tree-sha1 = "99b2ca5961ace1cd9fb05a4d6d8b9b4c10db1852"
os = "freebsd"

    [[gawk.download]]
    sha256 = "c00384438930c4198910e0895271282f8700231c98116a0017cf6d28a28d286b"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.3.1+0/gawk.v5.3.1.x86_64-unknown-freebsd.tar.gz"
