[[gawk]]
arch = "aarch64"
git-tree-sha1 = "137cd8687ac8e84a42b976a465ffc7f7841a6863"
os = "macos"

    [[gawk.download]]
    sha256 = "549a2a4b275c16b96c4b214f284ba8e2f678403c270b284e06c2b0c0c18bb17d"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.4.0+0/gawk.v5.4.0.aarch64-apple-darwin.tar.gz"
[[gawk]]
arch = "aarch64"
git-tree-sha1 = "eed0b1c87e7d05b3dc3ba6a6f7608645d473b9ee"
libc = "glibc"
os = "linux"

    [[gawk.download]]
    sha256 = "5dcf3f3665eda949abf9e221b02a0cbbf59ef293d1bcf0e7dc7c1b4bea8f971a"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.4.0+0/gawk.v5.4.0.aarch64-linux-gnu.tar.gz"
[[gawk]]
arch = "aarch64"
git-tree-sha1 = "c2bf1e520cd9d002e46fb34df4882f68f3a3a186"
libc = "musl"
os = "linux"

    [[gawk.download]]
    sha256 = "c2d60049c62cbda42bdb0ce05f5aaa2eb3557a50eb0d3af1bc41dc50fd95744d"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.4.0+0/gawk.v5.4.0.aarch64-linux-musl.tar.gz"
[[gawk]]
arch = "aarch64"
git-tree-sha1 = "0bf206daaaa0fbfc8256efd22a4fd883e7e2f9d7"
os = "freebsd"

    [[gawk.download]]
    sha256 = "78815f6f1b8a288318cc494e15673bc489a8a7d6397d649362a5ca257ae78f3b"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.4.0+0/gawk.v5.4.0.aarch64-unknown-freebsd.tar.gz"
[[gawk]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "897c0f61b2675d36f7f5ca3124006e3fece733f4"
libc = "glibc"
os = "linux"

    [[gawk.download]]
    sha256 = "71da185aec4a36b50bf13bc043fe891ee53000f2efc257408e3953eacb96deae"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.4.0+0/gawk.v5.4.0.armv6l-linux-gnueabihf.tar.gz"
[[gawk]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "285a89f30f6733faf9c550270bef17c57dd23b87"
libc = "musl"
os = "linux"

    [[gawk.download]]
    sha256 = "315c4da704642a96726cf5f875e79677d790e242dbbb63552c5e3182addd57be"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.4.0+0/gawk.v5.4.0.armv6l-linux-musleabihf.tar.gz"
[[gawk]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8acdcc4c59859fafdb1d163a2ea7fa177e9ad568"
libc = "glibc"
os = "linux"

    [[gawk.download]]
    sha256 = "52370ff9abf36e7a8aac68d1215716ebf808404d047497820d50009436c83bcb"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.4.0+0/gawk.v5.4.0.armv7l-linux-gnueabihf.tar.gz"
[[gawk]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "142f8926d9a325637fbc58ccc2768352307208bb"
libc = "musl"
os = "linux"

    [[gawk.download]]
    sha256 = "a95d373f9d197469407316e7f8ff9c6fe82b8f7068d0ca824c9bf7e7e6a2c9ba"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.4.0+0/gawk.v5.4.0.armv7l-linux-musleabihf.tar.gz"
[[gawk]]
arch = "i686"
git-tree-sha1 = "c771dd1c96356490c8db155626ea6c53a9a599ec"
libc = "glibc"
os = "linux"

    [[gawk.download]]
    sha256 = "ca5ca4b02122040b80f8fbbdb24e7ef53f131b4d6dcc329e6c54a35ec34cca75"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.4.0+0/gawk.v5.4.0.i686-linux-gnu.tar.gz"
[[gawk]]
arch = "i686"
git-tree-sha1 = "ebd3d9c3572247b40bd0984b35af3f2437e3c24c"
libc = "musl"
os = "linux"

    [[gawk.download]]
    sha256 = "13abd916e1a697f8540233a0dd86b313a77ccd2c3266c3e286fdb2e593b9cdb5"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.4.0+0/gawk.v5.4.0.i686-linux-musl.tar.gz"
[[gawk]]
arch = "powerpc64le"
git-tree-sha1 = "5d468304f54ba81418437030d682e59b35202c63"
libc = "glibc"
os = "linux"

    [[gawk.download]]
    sha256 = "6d9e7a9b85cb41d91bf2888712a25e82611f1fb38f4a0c1d2512acc919961b90"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.4.0+0/gawk.v5.4.0.powerpc64le-linux-gnu.tar.gz"
[[gawk]]
arch = "riscv64"
git-tree-sha1 = "8ab41a33158a63138c408be301609ae5a6a9d946"
libc = "glibc"
os = "linux"

    [[gawk.download]]
    sha256 = "d31004a419e6a8e1376e58e208d8627667ec248e9dd012e96d4eb1ed54b8066b"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.4.0+0/gawk.v5.4.0.riscv64-linux-gnu.tar.gz"
[[gawk]]
arch = "x86_64"
git-tree-sha1 = "c58503c251660f92f7662ca99d72b13d0706aa16"
os = "macos"

    [[gawk.download]]
    sha256 = "202200b50b1975816c6961b16cf61f72950c9921888189c48bfe68b72287105e"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.4.0+0/gawk.v5.4.0.x86_64-apple-darwin.tar.gz"
[[gawk]]
arch = "x86_64"
git-tree-sha1 = "25b31ccbf2250c0e220c8cf5ba6ff0b155330821"
libc = "glibc"
os = "linux"

    [[gawk.download]]
    sha256 = "e8c47fd4f4856667c6c3d3788a9e81b1b55a5ad6040ce8959923a89000b71009"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.4.0+0/gawk.v5.4.0.x86_64-linux-gnu.tar.gz"
[[gawk]]
arch = "x86_64"
git-tree-sha1 = "e8d62474f6a16008a927bd35496a168f73db3969"
libc = "musl"
os = "linux"

    [[gawk.download]]
    sha256 = "727d2b51e6a1dca769178421c44c7529a63be6299ddc2f828ef62f3cd5001b34"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.4.0+0/gawk.v5.4.0.x86_64-linux-musl.tar.gz"
[[gawk]]
arch = "x86_64"
git-tree-sha1 = "305d5bc2e86053587e1d2e471a4c8749b582e3a7"
os = "freebsd"

    [[gawk.download]]
    sha256 = "1de62c92bb43257e7a01c9897dca7c3dda2ec524b3331073e5666927472b45b2"
    url = "https://github.com/JuliaBinaryWrappers/gawk_jll.jl/releases/download/gawk-v5.4.0+0/gawk.v5.4.0.x86_64-unknown-freebsd.tar.gz"
